version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo  # ✅ backend depends on mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "5174:5173"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend  
      
volumes:
  mongo-data:
